app: fiap-hackathon-auth
service: fiap-hackathon-auth
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 3001
  CLIENTES_POOL_ID: ${ssm:/fiap-tech/cognito/client/user-pool/id}
  CLIENTES_POOL_CLIENT_ID: ${ssm:/fiap-tech/cognito/client/user-pool/client-id}
  CLIENTES_IDENTITY_POOL_ID: ${ssm:/fiap-tech/cognito/client/client-identity-pool/id}
  COGNITO_REGION: ${ssm:/fiap-tech/cognito/region}
  API_GATEWAY_API_ID: ${ssm:/fiap-tech/api_gateway/api_id}
  LAB_ROLE: ${ssm:/fiap-tech/lab_role}

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  region: us-east-1
  role:  ${self:custom.LAB_ROLE}
  stage: dev
  httpApi:
    id: ${self:custom.API_GATEWAY_API_ID}
  environment:
    CLIENTES_POOL_ID: ${self:custom.CLIENTES_POOL_ID}
    CLIENTES_POOL_CLIENT_ID: ${self:custom.CLIENTES_POOL_CLIENT_ID}
    CLIENTES_IDENTITY_POOL_ID: ${self:custom.CLIENTES_IDENTITY_POOL_ID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource: "*"

package:
  excludeDevDependencies: true

functions:
  authorization:
    handler: src/functions/auth/auth.handler
  signInClient:
    handler: src/functions/auth/signInClient.handler
    events:
      - httpApi:
          path: /login
          method: post